### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by parasaurolocus** [patxibocos/pcs-scraper#215]
Hello, after build the project with success I'm trying to launch the command but I'm receiving the following error message:

java -jar scraper/build/libs/scraper.jar -s 2023 -c cache -d out -f json

`Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/reflect/KProperty
	at io.github.patxibocos.pcsscraper.MainKt.<clinit>(Main.kt)
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.KProperty
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)`

I have tried with a clean installation in both CentOS 8 and MacOS Ventura computer with the same error message. On the other hand I can execute the built scraper.jar file inside the /release directory but the script has a date parse error after processing some data:

`Exception in thread "main" java.time.format.DateTimeParseException: Text '16 January 2024' could not be parsed at index 3`

Thanks.

**Comment by bmserras** [comment]
I am also getting this error with the latest code. Any help @patxibocos ?

**Comment by patxibocos** [comment]
Hello @parasaurolocus and @bmserras, thanks for reporting the issue!

As a quick workaround you can simply build with `./gradlew shadowJar` instead and it should work.
I'll try to look at the issue 👀

**Comment by bmserras** [comment]
@patxibocos That worked, thanks. But now it is giving out of bounds error when parsing the ranking. If I comment that code, it then gives the same error when parsing a team.

**Comment by patxibocos** [comment]
> [@patxibocos](https://github.com/patxibocos) That worked, thanks. But now it is giving out of bounds error when parsing the ranking. If I comment that code, it then gives the same error when parsing a team.

Do you mind sharing which exact season are you scraping? And also ensure you are runnning latest main version and disabling the cache?
